source_table_name :  <some-table>
source_driver : <some-driver>
source_user : <some-user-name>
source_columns : <some-columns>
source_jdbc : <some-jdbc>
target_table_name : <some target table>
target_driver : <target driver>
target : <jdbc>
target_user : <some user>
target_password  : <some-password>
target_columns  : <some-columns>
target_jdbc : <some-jdbc>
overloading_table : <yes/no>